export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVICE_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVICE_RESPONSE_SUCCESS";
export const LOGIN_USER_SERVICE_RESPONSE_FAILURE =
  "LOGIN_USER_SERVICE_RESPONSE_FAILURE";
